apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-reverse-proxy-app
  name: udagram-reverse-proxy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-reverse-proxy-app
  template:
    metadata:
      labels:
        service: udagram-reverse-proxy-app
    spec:
      containers:
      - image: femilawal/udagram-reverse-proxy
        name: udagram-reverse-proxy-app
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always


