apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-reverse-proxy-app
  name: udagram-reverse-proxy-app
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: udagram-reverse-proxy-app
  type: LoadBalancer 
